### ISSUE TITLE
adding a env.example file 

### ISSUE THREAD

**Issue by Eeshu-Yadav** [ivedantmistry/android_app#15]
adding a env.example file  so that users can Change the env.example file to .env and update it accordingly

**Comment by Eeshu-Yadav** [comment]
@ivedantmistry label it

**Comment by ivedantmistry** [comment]
@Eeshu-Yadav I'm maintaining Repositories for 3 years now, it would be good if i am not informed what to do and what not to especially in case like labelling repos. Hope you understand.

**Comment by Eeshu-Yadav** [comment]
@ivedantmistry i'm telling to label it for the sake of opening a pr on this , otherwise it won't be accepted . if this issue is not worth then i can close this .

**Comment by Eeshu-Yadav** [comment]
#18
