### ISSUE TITLE
SECRET KEY is exposed

### ISSUE THREAD

**Issue by Eeshu-Yadav** [ivedantmistry/android_app#5]
![Screenshot 2024-10-07 151757](https://github.com/user-attachments/assets/a3665c7f-22b8-4a29-8969-1f9413bc9492)
i will add **.gitignore** file in this project and also add the secret key detail in **.env** file .

**Comment by Eeshu-Yadav** [comment]
@ivedantmistry assingn this issue to me and add a label in it

**Comment by ivedantmistry** [comment]
how can you hide it?

**Comment by kavyachouhan** [comment]
> how can you hide it?

To hide the SECRET_KEY and other sensitive information in the Django project, I can implement environment variables

**Comment by Eeshu-Yadav** [comment]
@kavyachouhan  i have created this issue , then i have also capability of solving . if you are much excited to contribute then create an issue and send a pr . Thanks.

**Comment by ivedantmistry** [comment]
@kavyachouhan Hello you can work on this issue as well, but remember to create another branch and then raise pr by using it. Have a great day

**Comment by kavyachouhan** [comment]
> i have created this issue , then i have also capability of solving . if you are much excited to contribute then create an issue and send a pr . Thanks.

Thank you for your reply. I understand that you created the issue, and I appreciate your capabilities in solving it. However, since this is a security concern with the SECRET_KEY being exposed, I believe it's important to address it promptly to protect the integrity of the application.

Also, app is in development so there are many issues on which we can work together :)

**Comment by Eeshu-Yadav** [comment]
@ivedantmistry i have created this . how can assign to someone else ? . this is not good thing , bcze i have opened it yesterday and there is not too much time  to open this

**Comment by Eeshu-Yadav** [comment]
@ivedantmistry i have also tell in the image description , about how to be done it

**Comment by kavyachouhan** [comment]
@Eeshu-Yadav I appreciate your initiative in raising the issue. If you're actively working on it, that’s perfectly fine, and there's no need to feel angry.
I simply wanted to ensure that this security concern gets addressed promptly, given its importance.

**Comment by ivedantmistry** [comment]
@kavyachouhan @Eeshu-Yadav you both work on this issue and your boths PR get accepted as hacktoberfest-accepted
mind to create different branches while raising a PR

**Comment by Eeshu-Yadav** [comment]
@kavyachouhan i'm not angry , i'm just telling if someone takes too much to send a pr then you can ask admin to assign you , otherwise there is no point of asking it . this is not a race , some other person might be busy in doing the other stuff.

**Comment by kavyachouhan** [comment]
@Eeshu-Yadav My intention was to ensure that the security concern is addressed in a timely manner, but I understand that we’re all balancing different responsibilities. Let's both work on this issue.

**Comment by Eeshu-Yadav** [comment]
#13

**Comment by Eeshu-Yadav** [comment]
Resolves #13

**Comment by Eeshu-Yadav** [comment]
#13
