### ISSUE TITLE
Chnage the repository for the production environment

### ISSUE THREAD

**Issue by Eeshu-Yadav** [ivedantmistry/android_app#7]
![Screenshot 2024-10-07 191758](https://github.com/user-attachments/assets/29e91732-0465-41e6-b8d4-e3aa2e3c0fe2)
 this is not django structure for making the github repo . it usually make like this
![Screenshot 2024-10-07 183533](https://github.com/user-attachments/assets/76832a6a-60b5-40dc-bc3a-033dc3f63c39)
i will change the whole sturucture of it making for making professional and similar to production environment

**Comment by Eeshu-Yadav** [comment]
@ivedantmistry make the lablel of hacktoberfest in all the issues.

**Comment by ivedantmistry** [comment]
doesn't matter what we put label, hacktoberfest is marked when you raise a PR.
assigning this task to you.

**Comment by Eeshu-Yadav** [comment]
#10
