### ISSUE TITLE
shifting from local database like sqlite to production database like postgres

### ISSUE THREAD

**Issue by Eeshu-Yadav** [ivedantmistry/android_app#8]
generally sending the database details in  github is not a good practise . although it is a testing purpose db not for production purpose . so i will shift the whole tales to postgres and store the credentials in .env file

**Comment by ivedantmistry** [comment]
works

**Comment by Eeshu-Yadav** [comment]
#14

**Comment by Eeshu-Yadav** [comment]
@ivedantmistry it is not a good practise of push the database in github. usually users created on their own db using postgres or something and store the credentials in .env

**Comment by Eeshu-Yadav** [comment]
@ivedantmistry i have merges the pr regarding this issue , but it seems you have merged it with the master branch .  can you please tell me  the reason ? , because i have to the details regarding .env file and there is nothing like that in the master branch
