### ISSUE TITLE
Create Android App Skeleton

### ISSUE THREAD

**Issue by acriado-dev** [ivedantmistry/android_app#9]
Initialize the Andorid App project by creating the App with the functional structure only. The different reuqired views will be created only as a placeholder, and will be implemented in other issues/features.

According with the Initial project definition, the views that should be included in the App are:

- Home Screen (Login/Sign up)
- Chat List: Displays all current active conversations (if any)
- Chat Screen (indivisual)
- Contacts List (Allows to manage and search for contacts to chat)
- Settings

 @ivedantmistry Can you please assign me this issue? I would like to contribute with the project.

**Comment by ivedantmistry** [comment]
go ahead @acriado-dev and use email address only, not phone number for verification and using chat app. Also Integrate with backend. Best of Luck

**Comment by ivedantmistry** [comment]
@acriado-dev are you working on this?

**Comment by ivedantmistry** [comment]
Okay, looking forward for your PR, it would be good if you attach a working video of android app.
Thank you.
